version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./app/app/.env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - redis
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/app/.env

  redis:
    image: 'redis:7.0.8'

  celery:
    restart: always
    build: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    env_file:
      - ./app/app/.env
    depends_on:
      - redis
      - db

  celery-beat:
    restart: always
    build: .
    command: celery -A app beat -l info
    volumes:
      - ./app:/app
    env_file:
      - ./app/app/.env
    depends_on:
      - redis
      - db


volumes:
  postgres_data: